name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup C++ environment
      uses: aminya/setup-cpp@v1
      with:
        compiler: gcc-14
        cmake: true
        clang-format: true

    - name: Check coding style
      run: |
        FAILED=0
        FILES=$(find . \( -name "*.cc" -o -name "*.hpp" \) -not -path "*/json.hpp")
        for FILE in $FILES; do
          clang-format --dry-run -Werror "$FILE"
          if [ "$?" -ne 0 ]; then
            echo "clang-format failed for $FILE"
            FAILED=1
          fi
        done
        exit $FAILED

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build -j$(nproc)
