name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup C++ environment
      uses: aminya/setup-cpp@v1
      with:
        compiler: gcc-14
        cmake: true
        clang-format: true

    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build
